version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: PulsarForFlink
    user: root
    privileged: true
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./docker/data:/pulsar/data
      - ./docker/bootstrap.sh:/pulsar/bin/bootstrap.sh
    restart: always
    command: ["/pulsar/bin/bootstrap.sh"]
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      systemTopicEnabled: "true"
      topicLevelPoliciesEnabled: "true"
      transactionCoordinatorEnabled: "true"
  flink:
    image: streamnative/pulsar-flink:1.15.0.1
    container_name: Flink
    command: /bin/bash
    depends_on:
      - pulsar
  nifi:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    container_name: NiFi
    user: root
    privileged: true
    restart: always
    ports:
      - "9090:9090"
    environment:
      NIFI_WEB_HTTP_PORT: 9090
