version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: PulsarForFlink
    user: root
    privileged: true
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./docker/data:/pulsar/data
      - ./docker/bootstrap.sh:/pulsar/bin/bootstrap.sh
    restart: always
    command: ["/pulsar/bin/bootstrap.sh"]
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      systemTopicEnabled: "true"
      topicLevelPoliciesEnabled: "true"
      transactionCoordinatorEnabled: "true"
  flink:
    image: streamnative/pulsar-flink:1.15.0.1
    container_name: Flink
    command: /bin/bash
    depends_on:
      - pulsar
  nifi:
    image: apachenifi/nifi:1.19.0
    command: "bin/nifi.sh start"
    container_name: "nifi"
  restart: unless-stopped
    ports:
      - "8881:8881"
    environment:
      ########## JVM ##########
      
      # -Xms
      #   The initial JVM heap size.
      #NIFI_JVM_HEAP_INIT: 512m

      # -Xmx
      #   The maximum JVM heap size.
      #NIFI_JVM_HEAP_MAX: 512m
      
      # -Xdebug
      #   The JVM Debugger can be enabled by setting this environment variable to any value.
      #NIFI_JVM_DEBUGGER: ''

      ########## Web ##########

      # nifi.web.http.host
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      
      # nifi.web.http.port
      #   HTTP Port
      NIFI_WEB_HTTP_PORT: 8080

      # nifi.web.https.host
      #NIFI_WEB_HTTPS_HOST: '0.0.0.0'
      
      # nifi.web.https.port
      #   HTTPS Port
      #NIFI_WEB_HTTP_PORT: 8443
